name: Run linters

on: [push]

jobs:
  golang-ci-lint:
    name: Lint the project using GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
